apiVersion: apps/v1 #version of the API to use
kind: Deployment #what kind of object we're deploying
metadata: #information about our object we're deploying
  name: tax-deployment #name of the deployment
  labels: #a labels on the deployments created
    app: tax
spec: #specifications for our object
  replicas: 1 #the number of pods that should always be running
  selector: #which pods the replica set should be responsible for
    matchLabels:
      app: tax #any pods with labels matching this I'm responsible for
  template: #the pod template that gets deployed
    metadata:
      labels: #labels on the replica set and pods created
        app: tax
    spec:
      containers:
      - name: tax-container #the name of the container within the pod
        image: {{ .Values.tax.image }} #which container image should be pulled
        env:
        - name: DATABASE_URL
          value: 'mongodb://{{ .Values.tax.db.host }}:{{ .Values.tax.db.port }}/{{ .Values.tax.db.database }}?authSource=admin'
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: '{{ .Values.kafka.host }}:{{ .Values.kafka.port }}'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8020 #the port of the container within the pod
        resources:
          requests:  # The resources the Pod will request upon startup
            cpu: "1.5"  # equivalent to 0.1 of a CPU core
            memory: "2Gi"  # 128 Mebibytes of memory
          limits:  # The maximum resources the Pod can use
            cpu: "500m"  # up to 0.5 of a CPU core
            memory: "512Mi"  # up to 512 Mebibytes of memory
      restartPolicy: Always
      
---
apiVersion: v1 #version of the API to use
kind: Service #what kind of object we're deploying
metadata: #information about our object we're deploying
  name: tax-service #name of the service
  labels:
    app: tax
spec: #specifications for our object
#  type: NodePort #Ignore for now
  type: LoadBalancer #Ignore for now
  ports: #Ignore for now
  - protocol: TCP
    port: 8020
    targetPort: 8020
  selector: #label selector used to identify pods
    app: tax
