apiVersion: v1
kind: ConfigMap
metadata:
  name: tax-configmap
data:
  DATABASE_URL: 'mongodb://{{ .Values.tax.db.host }}:{{ .Values.tax.db.port }}/{{ .Values.tax.db.database }}?authSource=admin'
  KAFKA_BOOTSTRAP_SERVERS: '{{ .Values.kafka.host }}:{{ .Values.kafka.port }}'
