apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pv-claim
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka-app
spec:
  type: LoadBalancer
  ports:
    - name: 'http'
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka-app
spec:
  serviceName: kafka-svc
  replicas: 1
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: kafka-pv-claim
      containers:
        - name: kafka-container
          image: tamas99/kafka-kraft
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: REPLICAS
              value: '1'
            - name: SERVICE
              value: kafka-svc
            - name: NAMESPACE
              value: default
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INSIDE://:9092,OUTSIDE://10.10.132.193:9092"
            - name: SHARE_DIR
              value: /mnt/kafka
            # - name: KAFKA_LOG_DIRS
            #   value: "/kafka-logs"
          volumeMounts:
            - name: kafka-storage
              mountPath: /mnt/kafka
  # volumeClaimTemplates:
  #   - metadata:
  #       name: logs
  #     spec:
  #       storageClassName: "nfs-client"
  #       accessModes:
  #         - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 1Gi
