apiVersion: apps/v1 #version of the API to use
kind: Deployment #what kind of object we're deploying
metadata: #information about our object we're deploying
  name: tax-deployment #name of the deployment
  labels: #a labels on the deployments created
    app: tax
spec: #specifications for our object
  replicas: 1 #the number of pods that should always be running
  selector: #which pods the replica set should be responsible for
    matchLabels:
      app: tax #any pods with labels matching this I'm responsible for
  template: #the pod template that gets deployed
    metadata:
      labels: #labels on the replica set and pods created
        app: tax
    spec:
      containers:
      - name: tax-container #the name of the container within the pod
        image: {{ .Values.tax.image }} #which container image should be pulled
        envFrom:
        - configMapRef:
            name: tax-configmap
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8020 #the port of the container within the pod
        resources:
          requests:  # The resources the Pod will request upon startup
            cpu: "1.0"
            memory: "512Mi"
          limits:  # The maximum resources the Pod can use
            cpu: "1.0"
            memory: "1Gi"
      restartPolicy: Always
      
---
apiVersion: v1 #version of the API to use
kind: Service #what kind of object we're deploying
metadata: #information about our object we're deploying
  name: tax-service #name of the service
  labels:
    app: tax
spec: #specifications for our object
#  type: NodePort #Ignore for now
  type: LoadBalancer #Ignore for now
  ports: #Ignore for now
  - protocol: TCP
    port: 8020
    targetPort: 8020
  selector: #label selector used to identify pods
    app: tax
